[2024-05-18T01:19:11.278+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-18T01:19:11.329+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_pipelines_2.read_data scheduled__2024-05-17T00:00:00+00:00 [queued]>
[2024-05-18T01:19:11.344+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_pipelines_2.read_data scheduled__2024-05-17T00:00:00+00:00 [queued]>
[2024-05-18T01:19:11.347+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-05-18T01:19:11.366+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): read_data> on 2024-05-17 00:00:00+00:00
[2024-05-18T01:19:11.378+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=553) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-18T01:19:11.381+0000] {standard_task_runner.py:63} INFO - Started process 571 to run task
[2024-05-18T01:19:11.381+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_pipelines_2', 'read_data', 'scheduled__2024-05-17T00:00:00+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/data-ingestion-dag.py', '--cfg-path', '/tmp/tmpeio34qgh']
[2024-05-18T01:19:11.382+0000] {standard_task_runner.py:91} INFO - Job 145: Subtask read_data
[2024-05-18T01:19:11.473+0000] {task_command.py:426} INFO - Running <TaskInstance: data_ingestion_pipelines_2.read_data scheduled__2024-05-17T00:00:00+00:00 [running]> on host e512d0910ba5
[2024-05-18T01:19:11.665+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_pipelines_2' AIRFLOW_CTX_TASK_ID='read_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-17T00:00:00+00:00'
[2024-05-18T01:19:11.667+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-18T01:19:11.705+0000] {logging_mixin.py:188} INFO - file_path in read_data is  /opt/***/dags/raw-data/data_part_1.csv
[2024-05-18T01:19:11.731+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-18T01:19:11.732+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-18T01:19:11.752+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_ingestion_pipelines_2, task_id=read_data, run_id=scheduled__2024-05-17T00:00:00+00:00, execution_date=20240517T000000, start_date=20240518T011911, end_date=20240518T011911
[2024-05-18T01:19:11.798+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-18T01:19:11.856+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-18T01:19:11.862+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
