[2024-05-17T11:30:38.414+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-17T11:30:38.468+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_pipelines_2.read_data manual__2024-05-17T11:30:28.713644+00:00 [queued]>
[2024-05-17T11:30:38.481+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_pipelines_2.read_data manual__2024-05-17T11:30:28.713644+00:00 [queued]>
[2024-05-17T11:30:38.489+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-17T11:30:38.510+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): read_data> on 2024-05-17 11:30:28.713644+00:00
[2024-05-17T11:30:38.524+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=313) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-17T11:30:38.526+0000] {standard_task_runner.py:63} INFO - Started process 334 to run task
[2024-05-17T11:30:38.527+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_pipelines_2', 'read_data', 'manual__2024-05-17T11:30:28.713644+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/data-ingestion-dag.py', '--cfg-path', '/tmp/tmprnlodwc2']
[2024-05-17T11:30:38.529+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask read_data
[2024-05-17T11:30:38.602+0000] {task_command.py:426} INFO - Running <TaskInstance: data_ingestion_pipelines_2.read_data manual__2024-05-17T11:30:28.713644+00:00 [running]> on host 11a40e6e6344
[2024-05-17T11:30:38.768+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_pipelines_2' AIRFLOW_CTX_TASK_ID='read_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T11:30:28.713644+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-17T11:30:28.713644+00:00'
[2024-05-17T11:30:38.770+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-17T11:30:38.846+0000] {logging_mixin.py:188} INFO - file_path in read_data is  /opt/***/dags/raw-data/data_part_7.csv
[2024-05-17T11:30:38.869+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-17T11:30:38.870+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-17T11:30:38.899+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_ingestion_pipelines_2, task_id=read_data, run_id=manual__2024-05-17T11:30:28.713644+00:00, execution_date=20240517T113028, start_date=20240517T113038, end_date=20240517T113038
[2024-05-17T11:30:38.943+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-17T11:30:38.992+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-17T11:30:39.000+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
