[2024-05-17T20:35:56.699+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-17T20:35:56.736+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_pipelines_2.read_data manual__2024-05-17T12:31:17.083416+00:00 [queued]>
[2024-05-17T20:35:56.745+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_pipelines_2.read_data manual__2024-05-17T12:31:17.083416+00:00 [queued]>
[2024-05-17T20:35:56.747+0000] {taskinstance.py:2306} INFO - Starting attempt 19 of 19
[2024-05-17T20:35:56.762+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): read_data> on 2024-05-17 12:31:17.083416+00:00
[2024-05-17T20:35:56.774+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=9881) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-17T20:35:56.776+0000] {standard_task_runner.py:63} INFO - Started process 9891 to run task
[2024-05-17T20:35:56.777+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_pipelines_2', 'read_data', 'manual__2024-05-17T12:31:17.083416+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/data-ingestion-dag.py', '--cfg-path', '/tmp/tmp7yaydf2j']
[2024-05-17T20:35:56.779+0000] {standard_task_runner.py:91} INFO - Job 67: Subtask read_data
[2024-05-17T20:35:56.851+0000] {task_command.py:426} INFO - Running <TaskInstance: data_ingestion_pipelines_2.read_data manual__2024-05-17T12:31:17.083416+00:00 [running]> on host e512d0910ba5
[2024-05-17T20:35:56.958+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_pipelines_2' AIRFLOW_CTX_TASK_ID='read_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T12:31:17.083416+00:00' AIRFLOW_CTX_TRY_NUMBER='19' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-17T12:31:17.083416+00:00'
[2024-05-17T20:35:56.959+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-17T20:35:56.980+0000] {logging_mixin.py:188} INFO - file_path in read_data is  /opt/***/dags/raw-data/data_part_1.csv
[2024-05-17T20:35:56.995+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-17T20:35:56.995+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-17T20:35:57.009+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_ingestion_pipelines_2, task_id=read_data, run_id=manual__2024-05-17T12:31:17.083416+00:00, execution_date=20240517T123117, start_date=20240517T203556, end_date=20240517T203557
[2024-05-17T20:35:57.032+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-17T20:35:57.067+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-17T20:35:57.070+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
