[2024-05-18T02:08:02.716+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-18T02:08:02.903+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_pipelines_2.save_file scheduled__2024-05-17T00:00:00+00:00 [queued]>
[2024-05-18T02:08:02.949+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_pipelines_2.save_file scheduled__2024-05-17T00:00:00+00:00 [queued]>
[2024-05-18T02:08:02.951+0000] {taskinstance.py:2306} INFO - Starting attempt 7 of 7
[2024-05-18T02:08:02.983+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_file> on 2024-05-17 00:00:00+00:00
[2024-05-18T02:08:03.001+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1723) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-18T02:08:03.008+0000] {standard_task_runner.py:63} INFO - Started process 1774 to run task
[2024-05-18T02:08:03.009+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_pipelines_2', 'save_file', 'scheduled__2024-05-17T00:00:00+00:00', '--job-id', '182', '--raw', '--subdir', 'DAGS_FOLDER/data-ingestion-dag.py', '--cfg-path', '/tmp/tmpuya6_889']
[2024-05-18T02:08:03.011+0000] {standard_task_runner.py:91} INFO - Job 182: Subtask save_file
[2024-05-18T02:08:03.140+0000] {task_command.py:426} INFO - Running <TaskInstance: data_ingestion_pipelines_2.save_file scheduled__2024-05-17T00:00:00+00:00 [running]> on host 5ee845ef4e45
[2024-05-18T02:08:03.442+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_pipelines_2' AIRFLOW_CTX_TASK_ID='save_file' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-17T00:00:00+00:00'
[2024-05-18T02:08:03.444+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-18T02:08:03.848+0000] {logging_mixin.py:188} INFO - Saved good data to /opt/***/dags/good-data/data_part_10.csv
[2024-05-18T02:08:03.867+0000] {logging_mixin.py:188} INFO - Saved bad data to /opt/***/dags/bad-data/data_part_10.csv
[2024-05-18T02:08:03.872+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-18T02:08:03.873+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-18T02:08:03.907+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_ingestion_pipelines_2, task_id=save_file, run_id=scheduled__2024-05-17T00:00:00+00:00, execution_date=20240517T000000, start_date=20240518T020802, end_date=20240518T020803
[2024-05-18T02:08:03.962+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-18T02:08:03.985+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
